[tool.tbump.version]
current = "0.8.0.dev"
regex = '''
  (?P<major>\d+)\.(?P<minor>\d+)\.(?P<patch>\d+)(\.(?P<channel>dev))?
'''

[tool.tbump.git]
message_template = "Bump to {new_version}"
tag_template = "v{new_version}"

[[tool.tbump.before_commit]]
name = "check changelog"
cmd = "grep -q {new_version} CHANGELOG.md"

[[tool.tbump.file]]
src = "nbgrader/_version.py"
version_template = '({major}, {minor}, {patch}, "{channel}")'

[[tool.tbump.file]]
src = "pyproject.toml"

[[tool.tbump.file]]
src = "package.json"
search = '"version": "{current_version}"'

[[tool.tbump.file]]
src = "nbgrader/nbextensions/assignment_list/main.js"

[[tool.tbump.file]]
src = "nbgrader/nbextensions/course_list/main.js"

[[tool.tbump.file]]
src = "nbgrader/nbextensions/validate_assignment/main.js"

[[tool.tbump.field]]
name = "channel"
default = ""
